---
name: WWW-NioTV
version: v0.01
author:
  - 'Alec Chen <alec@cpan.org>'
abstract: retrieve TV information from http://www.niotv.com/
license: perl
resources:
  license: http://dev.perl.org/licenses/
build_requires:
  HTML::SimpleLinkExtor: 0
  HTML::TableExtract: 0
  List::MoreUtils: 0
  Test::More: 0
  WWW::Mechanize: 0
provides:
  WWW::NioTV:
    file: lib/WWW/NioTV.pm
    version: v0.01
generated_by: Module::Build version 0.2808
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
